task/home_work_3
MrSpock99/AndroidHomework pull request #2
Opened 2018-09-30 08:27 UTC by MrSpock99

2018-09-30 09:22 UTC, NailShaykhrazievItis requested changes

2018-09-30 09:22 UTC, NailShaykhrazievItis commented on app/src/main/java/apps/robot/homework_1/EditDialogFragment.kt
> +private const val ARG_TITLE = "ARG_TITLE"
можно было в companion oobjecte написать, он все ж относиться к этому классу

2018-09-30 09:22 UTC, NailShaykhrazievItis commented on app/src/main/java/apps/robot/homework_1/EditDialogFragment.kt
> +        val rootView = activity!!.layoutInflater.inflate(R.layout.fragment_edit_dialog, null)
!! - не приемлимы в кодстайле котлина. Основная фишка языка, в том что он нуллобезопасный, а ты говоришь явным образом, что здесь будет null и тебя эт не касается. Докапываться до этого сейчас смысла нет, но так на будущее, как пройдем котлин, такой код не буду принимать

2018-09-30 09:22 UTC, NailShaykhrazievItis commented on app/src/main/java/apps/robot/homework_1/EditDialogFragment.kt
> +
extra line

2018-09-30 09:22 UTC, NailShaykhrazievItis commented on app/src/main/java/apps/robot/homework_1/EditDialogFragment.kt
> +                .setNegativeButton(getString(R.string.cancel)) { dialog, which ->
вместо which -> _

2018-09-30 09:22 UTC, NailShaykhrazievItis commented on app/src/main/java/apps/robot/homework_1/EditDialogFragment.kt
> +                    val login = rootView.findViewById<EditText>(R.id.et_login).text.toString()
у тебя подключены андроид экстеншены, и ты не используешь их главную фичу. Зачем тогда подключать их? Или выруби их или напиши rootView.et_loogin.text.toString

2018-09-30 09:22 UTC, NailShaykhrazievItis commented on app/src/main/java/apps/robot/homework_1/EditDialogFragment.kt
> +        @JvmStatic
А у тебя есть джава классы?

2018-09-30 09:22 UTC, NailShaykhrazievItis commented on app/src/main/java/apps/robot/homework_1/EditDialogFragment.kt
> +                EditDialogFragment().apply {
Красиво, это сейчас студия сама так генерит?Ибо я сам до этого дошел не сразу и писал по старинке

2018-09-30 09:22 UTC, NailShaykhrazievItis commented on app/src/main/java/apps/robot/homework_1/EditDialogFragment.kt
> +    override fun onAttach(context: Context) {
Методы жц располагают по их жизненному циклу))то есть attach, create, resume, pause, destroy, detach

2018-09-30 09:22 UTC, NailShaykhrazievItis commented on app/src/main/java/apps/robot/homework_1/FavoritesFragment.kt
> +
extra line

2018-09-30 09:22 UTC, NailShaykhrazievItis commented on app/src/main/java/apps/robot/homework_1/FavoritesFragment.kt
> +        // Inflate the layout for this fragment
через равно можно написать

2018-09-30 09:22 UTC, NailShaykhrazievItis commented on app/src/main/java/apps/robot/homework_1/MessageFragment.kt
> +        return inflater.inflate(R.layout.fragment_message, container, false)
=

2018-09-30 09:22 UTC, NailShaykhrazievItis commented on app/src/main/java/apps/robot/homework_1/NavigationDrawerActivity.kt
> +        val tvHeaderLogin = findViewById<TextView>(R.id.tv_header_login)
андроид экстеншены

2018-09-30 09:22 UTC, NailShaykhrazievItis commented on app/src/main/java/apps/robot/homework_1/NavigationDrawerActivity.kt
> +    override fun onEdit(login: String, email: String) {
Методы импелементации идут после методов родительского класса

2018-09-30 09:22 UTC, NailShaykhrazievItis commented on app/src/main/java/apps/robot/homework_1/NavigationDrawerActivity.kt
> +        val profileFragment = supportFragmentManager.findFragmentByTag(ProfileFragment.toString()) as ProfileFragment
я тут сомневаюсь в as. Во первых ты не безопасно кастуешь, во вторых is вполне хватает(как мне кажется)

2018-09-30 09:22 UTC, NailShaykhrazievItis commented on app/src/main/java/apps/robot/homework_1/NavigationDrawerActivity.kt
> +
extra line

2018-09-30 09:22 UTC, NailShaykhrazievItis commented on app/src/main/java/apps/robot/homework_1/NavigationDrawerActivity.kt
> +        when (item.itemId) {
напиши return перед when, а другие return-ы удали

2018-09-30 09:22 UTC, NailShaykhrazievItis commented on app/src/main/java/apps/robot/homework_1/NavigationDrawerActivity.kt
> +        drawer_layout.closeDrawer(GravityCompat.START)
А тут точно должен быть старт, сомнения у меня. если я правильно помню в метод можно ничего не передавать

2018-09-30 09:22 UTC, NailShaykhrazievItis commented on app/src/main/java/apps/robot/homework_1/ProfileFragment.kt
> +        val btnEdit = rootView!!.findViewById<Button>(R.id.btn_edit)
андроид экстеншены

2018-09-30 09:22 UTC, NailShaykhrazievItis commented on app/src/main/java/apps/robot/homework_1/ProfileFragment.kt
> +        val tvLogin = view!!.findViewById<TextView>(R.id.tv_user_login)
андроид экстеншены

2018-09-30 09:22 UTC, NailShaykhrazievItis commented on app/src/main/java/apps/robot/homework_1/ProfileFragment.kt
> +        @JvmStatic
бесполезная аннотация

2018-09-30 09:22 UTC, NailShaykhrazievItis commented on app/src/main/res/menu/activity_navigation_drawer_drawer.xml
> +
extra line

2018-09-30 10:04 UTC, MrSpock99 commented on app/src/main/java/apps/robot/homework_1/EditDialogFragment.kt
> +        val rootView = activity!!.layoutInflater.inflate(R.layout.fragment_edit_dialog, null)
А что лучше здесь использовать? 
? - этот оператор?

2018-09-30 10:51 UTC, MrSpock99 commented on app/src/main/java/apps/robot/homework_1/EditDialogFragment.kt
> +        @JvmStatic
MainActivity был Java классом

2018-09-30 10:51 UTC, MrSpock99 commented on app/src/main/java/apps/robot/homework_1/EditDialogFragment.kt
> +                EditDialogFragment().apply {
Да, это студия

2018-09-30 10:59 UTC, MrSpock99 commented on app/src/main/java/apps/robot/homework_1/NavigationDrawerActivity.kt
> +        val profileFragment = supportFragmentManager.findFragmentByTag(ProfileFragment.toString()) as ProfileFragment
А почему это небезопасно?

2018-09-30 11:26 UTC, MrSpock99 commented on app/src/main/java/apps/robot/homework_1/NavigationDrawerActivity.kt
> +        drawer_layout.closeDrawer(GravityCompat.START)
Это студия сгенерировала, если туда ничего не передать, то студия ругается

2018-10-01 11:57 UTC, NailShaykhrazievItis approved these changes

2018-10-06 19:09 UTC, closed without merging